CRUD Auth and Users with HTTP
Fiu-Fit/api-gateway pull request #13
Opened 2023-05-03 01:04 UTC by MartinUgarte

2023-05-03 14:08 UTC, ianshih2003 requested changes

2023-05-03 14:08 UTC, ianshih2003 commented on src/modules/auth/auth.service.ts
>      return firstValueFrom(this.svc.validate({ token }));
cambiar a ue use http

2023-05-03 14:08 UTC, ianshih2003 commented on src/modules/user/user.controller.ts
> +    // eslint-disable-next-line no-console
innecesario

2023-05-03 14:08 UTC, ianshih2003 commented on src/modules/auth/auth.module.ts
> +  imports:     [ConfigModule.forRoot(), HttpModule.register({})],
El httpModule puede recibir un objeto con la propiedad `baseUrl`

```
imports:     [ConfigModule.forRoot(), HttpModule.register({
    baseURL: process.env.USER_SERVICE_URL
  })]
```

2023-05-03 19:36 UTC, MartinUgarte commented on src/modules/auth/auth.module.ts
> +  imports:     [ConfigModule.forRoot(), HttpModule.register({})],
Ok y para que sirve si ya le indico la URL a las requests?

2023-05-03 21:32 UTC, ianshih2003 commented on src/modules/auth/auth.module.ts
> +  imports:     [ConfigModule.forRoot(), HttpModule.register({})],
asi no lo tenes que repetir

2023-05-03 21:32 UTC, ianshih2003 requested changes

2023-05-03 21:32 UTC, ianshih2003 commented on src/modules/auth/auth.controller.ts
> +/* eslint-disable no-console */
Borrar

2023-05-03 21:57 UTC, ManuSanchez02 requested changes

2023-05-03 21:57 UTC, ManuSanchez02 commented on src/modules/auth/auth.controller.ts
> +  }*/
Porque esta comentado?

2023-05-03 23:12 UTC, ManuSanchez02 approved these changes

2023-05-04 00:07 UTC, ianshih2003 approved these changes

2023-05-04 02:40 UTC, merged